version: 2
jobs:
  build:
    working_directory: ~/App
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - android
