version: "3"
services:
  web:
    image: circleci/node:7.10
    ports:
      - "80:5000"
    links:
      - mongorestore
    command: yarn server
  mongo:
    image: mongo
  mongorestore:
    build: ./server/mongorestore
    image: travel_mongorestore:1.0
    depends_on:
      - mongo


