version: "3"
services:
  web:
    build: ./server/web
    image: travel_web:1.2
    ports:
      - "3000:3000"
    links:
      - mongorestore
  mongo:
    image: mongo
  mongorestore:
    build: ./server/mongorestore
    image: travel_mongorestore:1.0
    depends_on:
      - mongo


