version: "3"
services:
  web:
    build: ./server/web
    image: travel_web:1.0
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongorestore
  mongo:
    image: mongo
    ports:
      - 27017:27017
  mongorestore:
    build: ./server/mongorestore
    image: travel_mongorestore:1.0
    depends_on:
      - mongo



