version: "3"
services:
  web:
    build: ./server/web
    ports:
      - "80:5000"
    links:
      - mongorestore
  mongo:
    image: mongo
  mongorestore:
    build: ./server/mongorestore
    image: travel_mongorestore:1.0
    depends_on:
      - mongo


